<script setup>
import { useForm } from '@inertiajs/vue3';
import { ref } from 'vue';
import AdminDataTable from '../../Components/AdminDataTable.vue';
import Modal from '../../Components/Modal.vue';
import PortalLayout from '../../Layouts/PortalLayout.vue';
import SectionTitle from '../../Components/SectionTitle.vue';

const props = defineProps({ pdams: Object, provinces: Array, filters: Object });
const open = ref(false);
const editing = ref(null);
const form = useForm({ code: '', name: '', province_id: '', city: '', address: '' });
const showForm = (pdam = null) => { editing.value = pdam; form.clearErrors(); Object.assign(form, pdam ? { code: pdam.code, name: pdam.name, province_id: pdam.province_id, city: pdam.city || '', address: pdam.address || '' } : { code: '', name: '', province_id: '', city: '', address: '' }); open.value = true; };
const save = () => { const options = { preserveScroll: true, onSuccess: () => { open.value = false; form.reset(); } }; editing.value ? form.put(`/admin/pdams/${editing.value.id}`, options) : form.post('/admin/pdams', options); };
</script>

<template><PortalLayout portal="admin"><div class="page-head"><SectionTitle eyebrow="Master Data" title="Master PDAM" :meta="`${pdams.total} PDAM seluruh Indonesia`" /><button class="add" @click="showForm()">+ Tambah PDAM</button></div><AdminDataTable :paginator="pdams" :filters="filters" item-label="PDAM" search-placeholder="Cari nama, kode, atau kota" :filter-options="provinces.map(item => ({ value: String(item.id), label: item.name }))" v-slot="{ rows }"><table><thead><tr><th>Kode</th><th>Nama PDAM</th><th>Provinsi</th><th>Kota</th><th>Pemain</th><th></th></tr></thead><tbody><tr v-for="pdam in rows" :key="pdam.id"><td><strong>{{ pdam.code }}</strong></td><td>{{ pdam.name }}</td><td>{{ pdam.province?.name || '—' }}</td><td>{{ pdam.city || '—' }}</td><td>{{ pdam.members_count }}</td><td><div class="row-actions"><button @click="showForm(pdam)">Edit</button></div></td></tr></tbody></table></AdminDataTable><Modal :show="open" theme="light" max-width="2xl" @close="open=false"><form class="modal-form" @submit.prevent="save"><header><h3>{{ editing ? 'Edit PDAM' : 'Tambah PDAM' }}</h3><p>Data ini muncul pada pencarian asal pemain.</p></header><div class="grid"><label><span>Kode</span><input v-model="form.code" required></label><label><span>Nama PDAM</span><input v-model="form.name" required></label><label><span>Provinsi</span><select v-model="form.province_id" required><option value="">Pilih provinsi</option><option v-for="province in provinces" :key="province.id" :value="province.id">{{ province.name }}</option></select></label><label><span>Kota</span><input v-model="form.city"></label><label class="wide"><span>Alamat</span><textarea v-model="form.address" rows="3" /></label></div><small v-if="Object.keys(form.errors).length" class="error">Periksa kembali data wajib dan kode unik.</small><footer><button type="button" @click="open=false">Batal</button><button class="primary" :disabled="form.processing">Simpan</button></footer></form></Modal></PortalLayout></template>

<style scoped>.page-head{display:flex;align-items:end;justify-content:space-between;gap:16px;padding:8px 0 24px}.add,.modal-form footer button{min-height:40px;padding:9px 14px;border:1px solid #bfd0da;border-radius:8px;background:#fff;color:#1946a3;font-weight:800;cursor:pointer}.modal-form{display:grid;gap:18px;padding:22px}.modal-form header h3{margin:0;color:#173346}.modal-form header p{margin:5px 0 0;color:#6d7e89;font-size:12px}.grid{display:grid;grid-template-columns:1fr 1.5fr;gap:14px}.grid label{display:grid;gap:6px}.grid span{color:#526875;font-size:10px;font-weight:800;text-transform:uppercase}.grid input,.grid select,.grid textarea{width:100%;padding:10px 12px;border:1px solid #cedbe1;border-radius:8px}.wide{grid-column:1/-1}.modal-form footer{display:flex;justify-content:flex-end;gap:9px}.modal-form footer .primary{color:#fff;background:#1946a3;border-color:#1946a3}.error{color:#a1432e}@media(max-width:700px){.page-head{align-items:stretch;flex-direction:column}.grid{grid-template-columns:1fr}.wide{grid-column:auto}}</style>
